### ISSUE TITLE
Can you add action revert code ?

### ISSUE THREAD

**Issue by taimaiduc** [ses4j/tgit-st3#7]
Can you add action revert code ?

**Comment by ses4j** [comment]
Hi @taimaiduc, thanks for writing.  Personally, when I want to revert some things, I choose `Commit (repo)...` and revert whatever files I want from the popup that comes up.  

If that doesn't work 100% for you, describe why and I'll definitely consider the change.  I like keeping the list of options somewhat modest for clarity and speed, but am interested in others' workflows.

**Comment by taimaiduc** [comment]
Thanks for replying. Personally, I just want revert current file this action will helpful and faster. 👍 
Currently, i am using your way to revert file. Thanks
